### ISSUE TITLE
Albums in the Collection should show the Artist rather than AlbumArtist if AlbumArtist isn't set, but the Artist field is the same

### ISSUE THREAD

**Issue by solarnz** [tchaik/tchaik#43]
![collapsed](https://cloud.githubusercontent.com/assets/236589/7811661/78259b88-03ef-11e5-8f2e-459b0f266101.jpg)

![expanded](https://cloud.githubusercontent.com/assets/236589/7811660/7822c7f0-03ef-11e5-9746-1bb53c3eeb9b.jpg)

As you can see, the Artist is common throughout the group, but the AlbumArtist is not set, so the attribute does not show next to the Album name in the collection view when collapsed.

So, the front end sends
```
{"action":"FETCH","data":{"path":["Root"]}}
```

The server responds with 
```
...
            {
               "Key" : "9c509",
               "AlbumArtist" : "Brookes Brothers",
               "Name" : "Carry Me On (feat. Chrom3)"
            },
            {
               "Name" : "City Of Gold",
               "Key" : "2098b"
            },
            {
               "AlbumArtist" : "Logistics",
               "Key" : "5ea2a",
               "Name" : "Crash Bang Wallop!"
            },
...
```

And the tag for 'Artist' is consistent across the entire album, confirmed with picard.
![picard](https://cloud.githubusercontent.com/assets/236589/7811789/5b9e6bf6-03f0-11e5-9860-7dbc258c4384.png)

**Comment by dhowden** [comment]
Fixed in 06685fcc
