### ISSUE TITLE
Windows and http.Filesystem issues

### ISSUE THREAD

**Issue by kpashka** [tchaik/tchaik#56]
Hi, guys, thank you for great application, but I'm having a problem with it in Windows. When I launch tchaik like this:
```
$ tchaik -path "C:\Music" -debug true
```
I get error messages about invalid character in file path from artwork and filesystem submodules. And, obviously no artworks are being rendered, no files can be played in UI.

I've debugged this and found that these messages are generated by go stdlib package here:
https://golang.org/src/net/http/fs.go#36

I'm not sure yet, is it a bug in Go package, but is it really necessary to use http.File? My temporary workaround looks like this (patch for `store/filesystem.go`):

```go
// Open implements FileSystem.
func (fs *fileSystem) Open(ctx context.Context, path string) (http.File, error) {
	f, err := os.Open(path)
	return f, err
}
```

**Comment by solarnz** [comment]
Could you past the errors that you're getting?

**Comment by kpashka** [comment]
@solarnz sure:

```
Pavel@PAVEL-PC /e/Projects/src/tchaik.com/cmd/tchaik (master)
$ tchaik -path "C:\Users\Pavel\Music\iTunes\iTunes Media\Music\Compilations\FIFA 15" -debug true
Walking C:\Users\Pavel\Music\iTunes\iTunes Media\Music\Compilations\FIFA 15...
Finished walking.
Building Tchaik Library...done.
Building root collection...done.
Building artists filter...done.
Building recent index...done.
Building search index...done.
Loading play history...done.
Web server is running on http://localhost:8080
Quit the server with CTRL-C.
Debug path:  C:\Users\Pavel\Music\iTunes\iTunes Media\Music\Compilations\FIFA 15\11. Foster The People - Are You What You Want To Be.mp3
Media 2015/08/15 15:40:13 open error: http: invalid character in file path
Debug path:  C:\Users\Pavel\Music\iTunes\iTunes Media\Music\Compilations\FIFA 15\11. Foster The People - Are You What You Want To Be.mp3
Artwork 2015/08/15 15:40:13 open error: http: invalid character in file path
Debug path:  C:\Users\Pavel\Music\iTunes\iTunes Media\Music\Compilations\FIFA 15\11. Foster The People - Are You What You Want To Be.mp3
Artwork 2015/08/15 15:40:14 open error: http: invalid character in file path
```

I've patched `store/filesystem.go` a bit to print paths trying to be opened. All this paths are 100% valid.

**Comment by dhowden** [comment]
Thanks for the report, looking into it now.

FYI: if you add `-trace-listen localhost:4040` to the `tchaik` command, then you can see the full trace of the filesystem lookups at `http://localhost:4040/debug/requests` in your browser (see https://github.com/tchaik/tchaik#-trace-listen for a bit more info).

We can't just use os.Open because the config allows you to specify external sources (rather than things on your local machine).  This is where http.Dir is being included: https://github.com/tchaik/tchaik/blob/master/store/cmdflag/flag.go#L100.

**Comment by dhowden** [comment]
The problem is that `http.Dir` expects paths from a URL (i.e. using `/` as the separator), but we rewrite paths into OS-style paths and *then* pass them to `http.Dir`.  This is only a problem on Windows.

**Comment by kpashka** [comment]
@dhowden Thanks for the efficient response, but now I get this errors:

```
Media 2015/08/15 16:14:42 open error: open \C:\Users\Pavel\Music\iTunes\iTunes Media\Music\Compilations\FIFA 15\11. Foster The People - Are You What You Want To Be.mp3: The filename, directory name, or volume label syntax is incorrect.
Artwork 2015/08/15 16:14:42 open error: open \C:\Users\Pavel\Music\iTunes\iTunes Media\Music\Compilations\FIFA 15\11. Foster The People - Are You What You Want To Be.mp3: The filename, directory name, or volume label syntax is incorrect.
```

Looks like `filepath.ToSlash()` is not working properly on windows too - there shouldn't be any slashes before VolumeName

**Comment by dhowden** [comment]
Yes, I saw this was being added in `http.Dir`: https://golang.org/src/net/http/fs.go#44.  Not sure how I can get around this.  Will have a look.

**Comment by dhowden** [comment]
Did you get the trace stuff working? Can you send me the trace output for the request?

**Comment by kpashka** [comment]
@dhowden I would like to help, but for some reason, `-trace-listen` flag is not working for me, investigating this...

**Comment by kpashka** [comment]
@dhowden artwork error trace:

```
015/08/15 16:38:01.921593	0.000500	/0ddc68abb5805716424c5dcb6d72a42fb33d90be
16:38:01.921593	 .      	... libraryFileSystem: open: /0ddc68abb5805716424c5dcb6d72a42fb33d90be
16:38:01.921593	 .      	... local artworkstore: open: C:/Users/Pavel/Music/iTunes/iTunes Media/Music/Compilations/FIFA 15/11. Foster The People - Are You What You Want To Be.mp3
16:38:01.921593	 .      	... localstore (/): open: C:/Users/Pavel/Music/iTunes/iTunes Media/Music/Compilations/FIFA 15/11. Foster The People - Are You What You Want To Be.mp3
16:38:01.921593	 .      	... localstore (/): error opening: C:/Users/Pavel/Music/iTunes/iTunes Media/Music/Compilations/FIFA 15/11. Foster The People - Are You What You Want To Be.mp3
16:38:01.921593	 .      	... local artworkstore: error opening: C:/Users/Pavel/Music/iTunes/iTunes Media/Music/Compilations/FIFA 15/11. Foster The People - Are You What You Want To Be.mp3
16:38:01.922093	 .   500	... libraryFileSystem: error opening: /0ddc68abb5805716424c5dcb6d72a42fb33d90be
```

Track error trace:
```
015/08/15 16:38:01.841624	0.003000	/0ddc68abb5805716424c5dcb6d72a42fb33d90be
16:38:01.841624	 .      	... libraryFileSystem: open: /0ddc68abb5805716424c5dcb6d72a42fb33d90be
16:38:01.841624	 .      	... localstore (/): open: C:/Users/Pavel/Music/iTunes/iTunes Media/Music/Compilations/FIFA 15/11. Foster The People - Are You What You Want To Be.mp3
16:38:01.843625	 .  2000	... localstore (/): error opening: C:/Users/Pavel/Music/iTunes/iTunes Media/Music/Compilations/FIFA 15/11. Foster The People - Are You What You Want To Be.mp3
16:38:01.844624	 .  1000	... libraryFileSystem: error opening: /0ddc68abb5805716424c5dcb6d72a42fb33d90be
```

**Comment by dhowden** [comment]
Ah ha!  Ok, so you need to set `-local-store` (which is defaulting to `/`).

Try adding the params: `-local-store C:\Music -trim-path-prefix C:\Music`

**Comment by kpashka** [comment]
@dhowden Thanks, it worked!
