### ISSUE TITLE
Not working on new installation

### ISSUE THREAD

**Issue by tonyalaribe** [tchaik/tchaik#62]
I followed the instructions for installation, but when i visit localhost:8080, i see  a black page with no content. The javascript console shows a single error which says 

`
Player.js:179 Uncaught TypeError: Cannot read property 'id' of null
`

I'm not yet familiar with the codebase, so  i cant go farther than that yet.

**Comment by tonyalaribe** [comment]
I'm afraid the issue persists. I'm on linux, accessing it from chrome, if that makes any  difference

**Comment by dhowden** [comment]
Exactly the same error? That code has been replaced, you will need to pull and then rebuild the JS.

**Comment by tonyalaribe** [comment]
I missed the gulp build step, after pulling the code. Everying works now. 
Thank you
