### ISSUE TITLE
Better youtube-dl

### ISSUE THREAD

**Issue by MaxLeiter** [tchaik/tchaik#65]
Nothing I download with `youtube-dl` seems to be picked up by tchaik.

**Comment by dhowden** [comment]
That's strange.  It's possible that the metadata isn't being added by `youtube-dl`.  Have a look at the `tag` tool in https://github.com/dhowden/tag:

```
$ go get github.com/dhowden/tag/...
$ cd $GOPATH/bin
$ ./tag <yourfile>
```

This should tell you which tags are being picked up (it's the tab library used by tchaik to read music files).

**Comment by MaxLeiter** [comment]
Hm yeah, had to --add-metadata with youtubedl
